{
  ("p5");
  [
    {
      d_d: "1",
      ognoo: "11/21/2019",
      dansnii_dugaar: "1201",
      dansnii_ner: "авлага",
      debit_credit: "D",
      khariltsagch: "ABC",
      guilgeenii_utga: "Борлуулалт",
      dun: "10000",
      mgtmur: "1.1.1",
    },
    {
      d_d: "1",
      ognoo: "11/21/2019",
      dansnii_dugaar: "5101",
      dansnii_ner: "Брлт орлого",
      debit_credit: "C",
      khariltsagch: "ABC",
      guilgeenii_utga: "Борлуулалт",
      dun: "10000",
      mgtmur: null,
    },
    {
      d_d: "2",
      ognoo: "11/21/2019",
      dansnii_dugaar: "7022",
      dansnii_ner: "түрээс",
      debit_credit: "D",
      khariltsagch: "DEF",
      guilgeenii_utga: "ТҮрээс",
      dun: "5000",
      mgtmur: null,
    },
    {
      d_d: "2",
      ognoo: "11/21/2019",
      dansnii_dugaar: "1103",
      dansnii_ner: "Банкны данс",
      debit_credit: "C",
      khariltsagch: "DEF",
      guilgeenii_utga: "ТҮрээс",
      dun: "3000",
      mgtmur: "1.2.4",
    },
    {
      d_d: "2",
      ognoo: "11/21/2019",
      dansnii_dugaar: "3104",
      dansnii_ner: "Түрээсийн өглөг",
      debit_credit: "C",
      khariltsagch: "DEF",
      guilgeenii_utga: "ТҮрээс",
      dun: "2000",
      mgtmur: null,
    },
    {
      d_d: "3",
      ognoo: "11/30/2019",
      dansnii_dugaar: "7013",
      dansnii_ner: "Татварын зардал",
      debit_credit: "D",
      khariltsagch: "MTA",
      guilgeenii_utga: "Татвар тооцов",
      dun: "50",
      mgtmur: null,
    },
    {
      d_d: "3",
      ognoo: "11/30/2019",
      dansnii_dugaar: "3109",
      dansnii_ner: "ааноат",
      debit_credit: "C",
      khariltsagch: "MTA",
      guilgeenii_utga: "Татвар тооцов",
      dun: "50",
      mgtmur: null,
    },
    {
      d_d: "4",
      ognoo: "11/30/2019",
      dansnii_dugaar: "4201",
      dansnii_ner: "хур. ашиг",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Хаалтын бичилт",
      dun: "35958996",
      mgtmur: null,
    },
    {
      d_d: "4",
      ognoo: "11/30/2019",
      dansnii_dugaar: "9001",
      dansnii_ner: "OZND",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Хаалтын бичилт",
      dun: "35958996",
      mgtmur: null,
    },
    {
      d_d: "5",
      ognoo: "11/15/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Цалингийн Урьдчилгаа",
      dun: "10082811",
      mgtmur: "1.2.1",
    },
    {
      d_d: "5",
      ognoo: "11/15/2019",
      dansnii_dugaar: "9002",
      dansnii_ner: "Цалингийн тооцоо",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Цалингийн Урьдчилгаа",
      dun: "10082811",
      mgtmur: null,
    },
    {
      d_d: "6",
      ognoo: "11/30/2019",
      dansnii_dugaar: "7001",
      dansnii_ner: "Цалин зардал (Уд)",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Сүүл.цалин",
      dun: "21512500",
      mgtmur: null,
    },
    {
      d_d: "6",
      ognoo: "11/30/2019",
      dansnii_dugaar: "7002",
      dansnii_ner: "Цалин зардал (Бор)",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Сүүл.цалин",
      dun: "5874192",
      mgtmur: null,
    },
    {
      d_d: "6",
      ognoo: "11/30/2019",
      dansnii_dugaar: "9002",
      dansnii_ner: "Цалингийн тооцоо",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Сүүл.цалин",
      dun: "10082811",
      mgtmur: null,
    },
    {
      d_d: "6",
      ognoo: "11/30/2019",
      dansnii_dugaar: "3106",
      dansnii_ner: "ндш өглөг",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Сүүл.цалин",
      dun: "2598095",
      mgtmur: null,
    },
    {
      d_d: "6",
      ognoo: "11/30/2019",
      dansnii_dugaar: "3103",
      dansnii_ner: "хаоат өглөг",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Сүүл.цалин",
      dun: "2196873",
      mgtmur: null,
    },
    {
      d_d: "6",
      ognoo: "11/30/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Сүүл.цалин",
      dun: "12508913",
      mgtmur: "1.2.1",
    },
    {
      d_d: "7",
      ognoo: "11/30/2019",
      dansnii_dugaar: "7011",
      dansnii_ner: "НДШ зардал (Уд)",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Байгууллагын НДШ",
      dun: "2689063",
      mgtmur: null,
    },
    {
      d_d: "7",
      ognoo: "11/30/2019",
      dansnii_dugaar: "7012",
      dansnii_ner: "НДШ зардал (Бор)",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Байгууллагын НДШ",
      dun: "734274",
      mgtmur: null,
    },
    {
      d_d: "7",
      ognoo: "11/30/2019",
      dansnii_dugaar: "3106",
      dansnii_ner: "ндш өглөг",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Байгууллагын НДШ",
      dun: "3423336",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT1",
      ognoo: "11/3/2019",
      dansnii_dugaar: "6101",
      dansnii_ner: "ББӨ",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "136000",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT1",
      ognoo: "11/3/2019",
      dansnii_dugaar: "1501",
      dansnii_ner: "Бараа мат",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "136000",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT2",
      ognoo: "11/8/2019",
      dansnii_dugaar: "6101",
      dansnii_ner: "ББӨ",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "710769",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT2",
      ognoo: "11/8/2019",
      dansnii_dugaar: "1501",
      dansnii_ner: "Бараа мат",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "710769",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT3",
      ognoo: "11/9/2019",
      dansnii_dugaar: "6101",
      dansnii_ner: "ББӨ",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "17769",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT3",
      ognoo: "11/9/2019",
      dansnii_dugaar: "1501",
      dansnii_ner: "Бараа мат",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "17769",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT4",
      ognoo: "11/9/2019",
      dansnii_dugaar: "6101",
      dansnii_ner: "ББӨ",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "14215",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT4",
      ognoo: "11/9/2019",
      dansnii_dugaar: "1501",
      dansnii_ner: "Бараа мат",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "14215",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT5",
      ognoo: "11/9/2019",
      dansnii_dugaar: "6101",
      dansnii_ner: "ББӨ",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "10662",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT5",
      ognoo: "11/9/2019",
      dansnii_dugaar: "1501",
      dansnii_ner: "Бараа мат",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "10662",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT6",
      ognoo: "11/10/2019",
      dansnii_dugaar: "6101",
      dansnii_ner: "ББӨ",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "108218",
      mgtmur: null,
    },
    {
      d_d: "COST IMPORT6",
      ognoo: "11/10/2019",
      dansnii_dugaar: "1501",
      dansnii_ner: "Бараа мат",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "COST IMPORT",
      dun: "108218",
      mgtmur: null,
    },
    {
      d_d: "SALES1",
      ognoo: "11/3/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43772",
      dun: "204000",
      mgtmur: "1.1.1",
    },
    {
      d_d: "SALES1",
      ognoo: "11/3/2019",
      dansnii_dugaar: "5101",
      dansnii_ner: "Брлт орлого",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43772",
      dun: "204000",
      mgtmur: null,
    },
    {
      d_d: "SALES2",
      ognoo: "11/8/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43777",
      dun: "1066154",
      mgtmur: "1.1.1",
    },
    {
      d_d: "SALES2",
      ognoo: "11/8/2019",
      dansnii_dugaar: "5101",
      dansnii_ner: "Брлт орлого",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43777",
      dun: "1066154",
      mgtmur: null,
    },
    {
      d_d: "SALES3",
      ognoo: "11/9/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43778",
      dun: "26654",
      mgtmur: "1.1.1",
    },
    {
      d_d: "SALES3",
      ognoo: "11/9/2019",
      dansnii_dugaar: "5101",
      dansnii_ner: "Брлт орлого",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43778",
      dun: "26654",
      mgtmur: null,
    },
    {
      d_d: "SALES4",
      ognoo: "11/9/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43778",
      dun: "21323",
      mgtmur: "1.1.1",
    },
    {
      d_d: "SALES4",
      ognoo: "11/9/2019",
      dansnii_dugaar: "5101",
      dansnii_ner: "Брлт орлого",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43778",
      dun: "21323",
      mgtmur: null,
    },
    {
      d_d: "SALES5",
      ognoo: "11/9/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43778",
      dun: "15992",
      mgtmur: "1.1.1",
    },
    {
      d_d: "SALES5",
      ognoo: "11/9/2019",
      dansnii_dugaar: "5101",
      dansnii_ner: "Брлт орлого",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43778",
      dun: "15992",
      mgtmur: null,
    },
    {
      d_d: "SALES6",
      ognoo: "11/10/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43779",
      dun: "162327",
      mgtmur: "1.1.1",
    },
    {
      d_d: "SALES6",
      ognoo: "11/10/2019",
      dansnii_dugaar: "5101",
      dansnii_ner: "Брлт орлого",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Sales @43779",
      dun: "162327",
      mgtmur: null,
    },
    {
      d_d: "FA1",
      ognoo: "7/1/2019",
      dansnii_dugaar: "2001",
      dansnii_ner: "Үндсэн хөр.",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "ҮХ худалдаж авав",
      dun: "222465600",
      mgtmur: null,
    },
    {
      d_d: "FA1",
      ognoo: "7/1/2019",
      dansnii_dugaar: "1001",
      dansnii_ner: "Касс",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "ҮХ худалдаж авав",
      dun: "222465600",
      mgtmur: "2.2.1",
    },
    {
      d_d: "FA2",
      ognoo: "12/31/2019",
      dansnii_dugaar: "7005",
      dansnii_ner: "элэгдэл",
      debit_credit: "D",
      khariltsagch: null,
      guilgeenii_utga: "Элэгдэл тооцов",
      dun: "12261201",
      mgtmur: null,
    },
    {
      d_d: "FA2",
      ognoo: "12/31/2019",
      dansnii_dugaar: "2010",
      dansnii_ner: "Үх-н хур.эл.",
      debit_credit: "C",
      khariltsagch: null,
      guilgeenii_utga: "Элэгдэл тооцов",
      dun: "12261201",
      mgtmur: null,
    },
  ];
}
