# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI 

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.12.0]
    env:
      VUE_WEBSITE_URL: ${{secrets.VUE_WEBSITE_URL}}
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: cd ./frontend/ && npm install
    - run: cd ./frontend/ && npm run build
    - run: cd ./frontend/ && cp -r dist/ ../
    - run: pm2 restart 0
    # - run: npm install -g @vue/cli
    # - run: ls
    # - run: npm install
    # - run: npm run build
    # - run: cp -r dist/ ../
    #   #  /frontend npm build
    # # cp /dist -> ../dict
    # - run: pm2 restart 0
